services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN:-portainer.local}`)
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.middlewares=portainer-auth
      - traefik.http.middlewares.portainer-auth.basicauth.users=admin:$$2y$$05$$CdpY7AVW.bmxlKWeZ3XoSOEPjgwcMdDKn7tEO.AR/piwgKjHFIwuG
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik-public

volumes:
  portainer-data:

networks:
  traefik-public:
    external: true
    name: traefik-public
