version: "3.3"

services:
  traefik:
    image: "traefik:v2.11"
    restart: unless-stopped
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Enable Traefik dashboard with authentication
      - traefik.http.routers.traefik-public-http.rule=Host(`${TRAEFIK_DOMAIN:-traefik.local}`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.service=api@internal
      - traefik.http.routers.traefik-public-http.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$05$$CdpY7AVW.bmxlKWeZ3XoSOEPjgwcMdDKn7tEO.AR/piwgKjHFIwuG
      # Enable metrics endpoint
      - traefik.http.routers.traefik-metrics.rule=Host(`${TRAEFIK_DOMAIN:-traefik.local}`) && PathPrefix(`/metrics`)
      - traefik.http.routers.traefik-metrics.entrypoints=http
      - traefik.http.routers.traefik-metrics.service=prometheus@internal
      - traefik.http.routers.traefik-metrics.middlewares=traefik-auth
      # Define the port inside of the Docker service to use
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker=true
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint http listening on port 80
      - --entrypoints.http.address=:80
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      # Enable metrics (Prometheus format)
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      # Enable tracing (Jaeger)
      - --tracing.jaeger=true
      - --tracing.jaeger.samplingType=const
      - --tracing.jaeger.samplingParam=1.0
    ports:
      - ${HTTP_PUBLISH_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
    external: false
